<p style="text-align:center; font-size:300%; line-height:300%; font-weight:bold; background-color:#2F52A3; color:white">Matrices</p>

<div style="font-weight:bold; background-color:#61C3CE">
    Evaluation :
    <ul>
        <li>Faire de calculs avec les matrices</li>
    </ul>
</div>

**Recommandations :**

+ Respectez rigoureusement la signature des fonctions (casse incluse), et les consignes.
+ Copiez-collez le code de votre fonction (ne contenant aucun print ou autre effet de bord) sur Moodle (CodeRunner)
+ Utilisez les alias définis ci-dessous. Ne faites pas d'import sur Moodle, c'est déjà fait.
+ Même si vous travaillez à plusieurs, faites un dépôt par personne.
+ Il n'y aura aucune "démo" dans les cinq dernières minutes. Ce travail et les tests Moodle seront pris en compte dans la note finale.
+ Vous allez coder **des fonctions**; cela signifie que vous **retournez** le résultat et que vous ne modifiez pas les paramètres (**pas d'effet de bord**).

**Objectif :**

+ Assimilier le vocabulaire sur les matrices, en mettant en place quelques fonctions.
+ Pratiquer les opérations de bases sur les matrices, en mettant en place quelques fonctions.

In [1]:
import numpy as np

<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Vocabulaire sur les matrices</p>

Codez les fonctions de test suivantes :
+ `estCarree(A)` qui retourne `True` si et seulement si la matrice (`np.array`) $A$ est carrée.
+ `estTriangulaireSuperieure(A)` qui retourne `True` si et seulement si la matrice $A$ est triangulaire supérieure.
+ `estSymetrique(A)` qui retourne `True` si et seulement si la matrice $A$ est symétrique.

**Indications :**
+ Si $A$ est une matrice, alors `np.shape(A)` ou `A.shape` retourne les dimensions de cette matrice.
+ Réfléchissez avant de coder : `while` ou `for` ?
+ Une matrice ne peut être triangulaire ou symétrique que si elle est déjà carrée.

In [16]:
def estCarree(A):return A.shape[0] == A.shape[1]

def estTriangulaireSuperieur(A):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i, j] != 0 and i > j:return False
    return True

def estSymetrique(A):
    if estCarree(A) == False:
        return False
    else:
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if A[i, j] != A[j, i]:return False
        return True
                   


True
False
True
True
False


<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Egalité matricielle</p>

**Instructions :**
+ L'objectif est de vous faire coder des fonctions dont le code parcours les coefficients des matrices. 
+ Vous **ne devez pas** utiliser les fonctions de haut niveau fournies par numpy, sauf lorsque cela sera explicitement demandé.
+ Ecrivez une fonction `egales(A,B)` qui teste l'égalité des deux matrices.
+ Codez une nouvelle fonction `estSymetriqueV2(A)` qui utilise la commande `np.transpose` ainsi que votre fonction d'égalité.

In [20]:
def egales(A, B):
    if A.shape == B.shape :
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if A[i, j] != B[i, j]:return False
        return True
    else:return False
            
def estSymetriqueV2(A):return egales(A, np.transpose(A))



True
False
True
True
False
False
False
True
True
False


<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Addition matricielle</p>

**Instructions :**
+ L'objectif est de vous faire coder des fonctions dont le code parcours les coefficients des matrices. 
+ Vous **ne devez pas** utiliser les fonctions de haut niveau fournies par numpy, sauf lorsque cela sera explicitement demandé.
+ Codez une fonction `addition(A,B)` qui retourne la somme des deux matrices lorsque cela est possible, `None` sinon.

**Indications :**
+ Réflichissez avant de coder : quand peut-on ajouter deux matrices ?
+ Réflichissez avant de coder (bis) : `while` ou `for` ?

In [21]:
def addition(A, B):
    if A.shape == B.shape:
        copy = np.copy(A)
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                copy[i, j] = A[i, j] + B[i, j]
        return copy
    else: return None


None
[[ 2  4  6]
 [ 2  2  8]
 [ 3  4 10]]


<p style="font-size:150%; line-height:150%; font-weight:bold; color:#D67D3A">Attention : </p>

Les fonctions à rendre pour ce TP sont :
+ `estCarree(A)`
+ `estTriangulaireSuperieure(A)`
+ `estSymetrique(A)`
+ `egales(A,B)`
+ `addition(A,B)`