<p style="text-align:center; font-size:300%; line-height:300%; font-weight:bold; background-color:#2F52A3; color:white">Algorithme du pivot de Gauss</p>

<div style="font-weight:bold; background-color:#61C3CE">
    Evaluation :
    <ul>
        <li>Résoudre des systèmes linéaires</li>
    </ul>
</div>

**Recommandations :**

+ Respectez rigoureusement la signature des fonctions (casse incluse), et les consignes.
+ Copiez-collez le code de votre fonction (ne contenant aucun print ou autre effet de bord) sur Moodle (CodeRunner)
+ Utilisez les alias définis ci-dessous.
+ Même si vous travaillez à plusieurs, faites un dépôt par personne.
+ Il n'y aura aucune "démo" dans les cinq dernières minutes. Ce travail et les tests Moodle seront pris en compte dans la note finale.
+ Vous allez coder **des fonctions**; cela signifie que vous **retournez** le résultat et que vous ne modifiez pas les paramètres (**pas d'effet de bord**).

**Objectif :**

+ Mettre en place l'algorithme de Gauss permettant de résoudre des systèmes linéaires.


In [1]:
"""
Exécutez cette cellule. 
Les instructions seront validées pour tout le notebook.
"""

import numpy as np # Importation de numpy
np.set_printoptions(precision=3, suppress=True) # Affichage des réels

<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Fonction d'échange de lignes</p>

Ecrivez une fonction `Echange(i,j,M)` qui retourne une matrice dans laquelle les lignes $i$ et $j$ ont été échangées.

Par exemple :

+ Avec $A = \left(\begin{matrix} 
1 & -3 & 2 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$, l'appel de `Echange(1,2,A)` doit retourner :
$\left(\begin{matrix} 
1 & -3 & 2 \\
5 & 11 & 3 \\
2 & 4 & -1 \\
\end{matrix}\right)$

+ Avec $B = \left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
2 & 8 & 6 & -4 & 2 \\
\end{matrix}\right)$, l'appel de `Echange(0,3,B)` doit retourner :
$\left(\begin{matrix} 
2 & 8 & 6 & -4 & 2 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
0 & 7 & -1 & 6 & 7 \\
\end{matrix}\right)$

**En Python, la matrice `M` doit être un `numpy.array`; `i` et `j` sont des entiers**

In [5]:
# Insérez et testez le code de votre fonction ici
def Echange(i, j, m):
    resultat = np.copy(m)
    resultat[i, :] = m[j, :]
    resultat[j, :] = m[i, :]
    return resultat

A = np.array([[1, -3, 2], [2, 4, -1], [5, 11, 3]])
print(Echange(1, 2, A))

[[ 1 -3  2]
 [ 5 11  3]
 [ 2  4 -1]]


<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Fonction de combinaison linéaire</p>

Ecrivez une fonction `CombinaisonLineaire(i,coeff,j,M)` qui retourne une matrice dans laquelle à la ligne $i$ a été ajoutée `coeff` fois la ligne $j$.

Par exemple :

+ Avec $A = \left(\begin{matrix} 
1 & -3 & 2 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$, l'appel de `CombinaisonLineaire(0,-5,1,A)` doit retourner :
$\left(\begin{matrix} 
-9 & -23 & 7 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$

+ Avec $B = \left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
2 & 8 & 6 & -4 & 2 \\
\end{matrix}\right)$, l'appel de `CombinaisonLineaire(3,-2,2,B)` doit retourner :
$\left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
0 & -2 & 24 & -10 & 12 \\
\end{matrix}\right)$

**En Python, le coefficient `coeff` est un nombre réel**

# Insérez et testez le code de votre fonction ici


In [8]:
def CombinaisonLineaire(i, coeff, j, M):
    res = np.copy(M)
    res[i, :] = M[i, :] + M[j, :] * coeff
    return res

print(CombinaisonLineaire(0, -5, 1, A))

[[ -9 -23   7]
 [  2   4  -1]
 [  5  11   3]]


<p style="font-size:150%; line-height:150%; font-weight:bold; background-color:#FFDD00">Exercice : Fonction de choix du pivot</p>

**Attention :** Cette fonction est un peu plus difficile. Lisez attentivement l'énoncé. Demandez à votre enseignant !

La fonction `ChoixPivot(j,M)` doit retourner, en cherchant dans la colonne $j$, le premier **indice** de ligne $i$ sous la diagonale (diagonale incluse) tel que $M_{i,j} \not= 0$. Si un tel coefficient n'existe pas, la fonction retourne `None`.

Par exemple avec la matrice :
$$A = \left(\begin{matrix}
0 & 1 & 2 & 3 \\
0 & 2 & 1 & 5 \\
1 & 0 & 0 & 4 \\
2 & 7 & 0 & 8 \\
\end{matrix}\right)$$

+ `ChoixPivot(0,A)` retourne $2$
+ `ChoixPivot(1,A)` retourne $1$ : Le coefficient sur la diagonale est non-nul
+ `ChoixPivot(2,A)` retourne None : Il n'y a pas de coefficient non-nul sous la diagonale dans cette colonne
+ `ChoixPivot(3,A)` retourne $3$

**Indication :** Vous pouvez récupérer les dimensions d'une matrice $M$ à l'aide de `np.shape(M)` ou bien `M.shape`.

In [19]:
# Insérez et testez le code de votre fonction ici
def ChoixPivot(j, M):
    for i in range(M.shape[0]):
        if M[i, j] != 0 and i >= j:
            return i
    return None

A = np.array([[0, 1, 2, 3], [0, 2, 1, 5], [1, 0, 0, 4], [2, 7, 0, 8]])
print(ChoixPivot(0, A))
print(ChoixPivot(1, A))
print(ChoixPivot(2, A))
print(ChoixPivot(3, A))

2
1
None
3


<p style="font-size:150%; line-height:150%; font-weight:bold; color:#D67D3A">Attention : </p>

Les fonctions à rendre pour ce TP sont :
+ `Echange(i, j, M)`
+ `CombinaisonLineaire(i, coeff, j , M)`
+ `ChoixPivot(j, M)`